import { expect, test } from '@playwright/test'

test('phone-first setup remains usable on a narrow screen', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'phone', 'Phone layout')
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /wherewolf moderator/i })).toBeVisible()
  await page.getByRole('button', { name: /^new game$/i }).click()
  await expect(page.locator('.setup-page > .page-heading')).toBeHidden()
  await expect(page.getByText('Choose role packs')).toBeVisible()
  await expect(page.locator('.bottom-nav')).toBeHidden()
  await page.getByRole('button', { name: /Darkest Night/ }).click()
  await page.getByRole('button', { name: /continue/i }).click()
  await expect(page.getByText('Who is playing?')).toBeVisible()
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  for (let index = 1; index <= 6; index += 1) await page.getByLabel(`Player ${index} name`).fill(`Player ${index}`)
  await page.getByRole('button', { name: /continue/i }).click()
  const rows = page.locator('.role-config-row')
  await expect(rows.filter({ hasText: 'Alpha Wolf' }).locator('.role-check input')).toBeChecked()
  await expect(rows.filter({ hasText: 'Outcast Wolf' }).locator('.role-check input')).not.toBeChecked()
  await expect(rows.first().getByText('Announced min')).toBeVisible()
  await expect(rows.first().getByText('Announced max')).toBeVisible()
  await expect(rows.first().getByText('In play')).toBeVisible()
  const rightEdges = await rows.first().locator('.role-config-control').evaluateAll((controls) => controls.map((control) => control.getBoundingClientRect().right))
  expect(Math.max(...rightEdges)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  await page.getByRole('button', { name: /select all/i }).click()
  await expect(rows.first().locator('.role-check input')).toBeChecked()
  await expect(rows.last().locator('.role-check input')).toBeChecked()
  await page.getByRole('button', { name: /clear all/i }).click()
  await expect(rows.first().locator('.role-check input')).not.toBeChecked()
  const farmerRow = rows.filter({ hasText: 'Farmer' })
  await farmerRow.locator('.role-check').click()
  await expect(farmerRow.locator('.stepper').nth(1).locator('span')).toHaveText('3')
  for (let index = 0; index < 6; index += 1) {
    await rows.nth(index).locator('.role-check').click()
    await expect(rows.nth(index).locator('.role-check input')).toBeChecked()
    await rows.nth(index).locator('.exact-checkbox').click()
  }
  await page.getByRole('button', { name: /continue/i }).click()
  await expect(page.locator('.segmented button')).toHaveCount(2)
  await expect(page.getByRole('button', { name: /random allocation/i })).toBeVisible()
  await expect(page.getByRole('button', { name: /gardened allocation/i })).toBeVisible()
  await expect(page.locator('.night-order > div')).toHaveCount(3)
  await expect(page.locator('.night-order')).toContainText('Alpha Wolf')
  await expect(page.locator('.night-order')).toContainText('Pack Wolf')
  await expect(page.locator('.night-order')).not.toContainText('Witch')
  await expect(page.locator('.night-order')).not.toContainText('Healer')
  await page.getByRole('button', { name: /deal roles & begin/i }).click()
  await expect(page.locator('.game-statusbar')).toContainText('N0')
  await expect(page.locator('.phase-card')).toBeVisible()
  await page.getByRole('button', { name: /^roster$/i }).click()
  await expect(page.locator('.current-properties')).toHaveCount(6)
  await page.locator('.current-properties summary').first().click()
  await expect(page.locator('.current-properties').first().locator('.property-chip')).not.toHaveCount(0)
  await page.locator('.secret-roster header button').click()
  await page.locator('.target-grid button').first().click()
  await page.getByRole('button', { name: /confirm 1 selection/i }).click()
  await page.getByRole('button', { name: /history/i }).click()
  await expect(page.locator('.trace-list article').first()).toBeVisible()
})

test('grouped setup actions wake matching roles together', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'phone', 'Phone moderation layout')
  await page.goto('/')
  await page.getByRole('button', { name: /^new game$/i }).click()
  await page.getByRole('button', { name: /silent night/i }).click()
  await expect(page.getByRole('button', { name: /silent night/i })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: /continue/i }).click()
  await page.locator('.player-row .danger').last().click()
  await page.locator('.player-row .danger').last().click()
  for (let index = 1; index <= 4; index += 1) await page.getByLabel(`Player ${index} name`).fill(`Player ${index}`)
  await page.getByRole('button', { name: /continue/i }).click()
  const rows = page.locator('.role-config-row')
  await page.getByRole('button', { name: /clear all/i }).click()
  for (let index = 0; index < 4; index += 1) {
    await rows.nth(index).locator('.role-check').click()
    await rows.nth(index).locator('.exact-checkbox').click()
  }
  await page.getByRole('button', { name: /continue/i }).click()
  await page.getByRole('button', { name: /deal roles & begin/i }).click()
  await expect(page.getByRole('heading', { name: 'Wolf Pack · Meet the Pack' })).toBeVisible()
  await expect(page.locator('.phase-instruction')).toContainText(/Wake Player \d, Player \d, and Player \d together\./)
  await expect(page.locator('.phase-instruction')).not.toContainText('Say “')
  await expect(page.locator('.wake-together')).toContainText('WAKE TOGETHER')
  await expect(page.locator('.wake-participants strong')).toHaveCount(3)
  await expect(page.locator('.action-information')).toContainText('Defector')
  await expect(page.locator('.action-information')).toContainText('In play')
  await page.getByRole('button', { name: /^confirm$/i }).click()
  await expect(page.getByRole('heading', { name: 'Day 1 discussion' })).toBeVisible()
})

test('moderator text states the burn, night outcome and winners', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'phone', 'Phone moderation layout')
  await page.goto('/')
  await page.getByRole('button', { name: /^new game$/i }).click()
  await page.getByRole('button', { name: /continue/i }).click()
  for (let count = 0; count < 3; count += 1) await page.locator('.player-row .danger').last().click()
  await page.getByLabel('Player 1 name').fill('Alice')
  await page.getByLabel('Player 2 name').fill('Bob')
  await page.getByLabel('Player 3 name').fill('Wolf')
  await page.getByRole('button', { name: /continue/i }).click()
  const alphaRow = page.locator('.role-config-row').filter({ hasText: 'Alpha Wolf' })
  const farmerRow = page.locator('.role-config-row').filter({ hasText: 'Farmer' })
  await page.getByRole('button', { name: /clear all/i }).click()
  await alphaRow.locator('.role-check').click()
  await alphaRow.locator('.exact-checkbox').click()
  await farmerRow.locator('.role-check').click()
  await farmerRow.locator('.stepper').nth(2).getByRole('button').last().click()
  await farmerRow.locator('.stepper').nth(2).getByRole('button').last().click()
  await page.getByRole('button', { name: /continue/i }).click()
  await page.getByRole('button', { name: /gardened allocation/i }).click()
  const assignments = page.locator('.assignment-list select')
  await assignments.nth(0).selectOption({ label: 'Farmer' })
  await assignments.nth(1).selectOption({ label: 'Farmer' })
  await assignments.nth(2).selectOption({ label: 'Alpha Wolf' })
  await page.getByRole('button', { name: /deal roles & begin/i }).click()
  await page.getByRole('button', { name: /^confirm$/i }).click()
  await page.getByRole('button', { name: /begin first vote/i }).click()
  await expect(page.locator('.vote-list .tag')).toHaveCount(0)
  await page.getByLabel('Wolf votes').fill('3')
  await page.getByRole('button', { name: /record vote/i }).click()
  await expect(page.getByRole('heading', { name: 'The village has decided to burn Wolf.' })).toBeVisible()
  await page.getByRole('button', { name: /continue to night/i }).click()
  await expect(page.getByRole('heading', { name: 'Call Alpha Wolf' })).toBeVisible()
  await expect(page.locator('.phase-instruction')).toContainText('Alpha Wolf, wake up and choose a player to bite.')
  await page.getByRole('button', { name: /continue night order/i }).click()
  await expect(page.getByRole('heading', { name: 'No night attack was made.' })).toBeVisible()
  await page.getByRole('button', { name: /^continue$/i }).click()
  await expect(page.getByRole('heading', { name: 'Village victory' })).toBeVisible()
  await expect(page.getByText('Alice, Bob win the game.')).toBeVisible()
  await expect(page.locator('.winner-list')).toContainText('Alice')
  await expect(page.locator('.winner-list')).toContainText('Bob')
})

test('Ballot vote starts with a fresh zero tally', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'phone', 'Phone moderation layout')
  await page.goto('/')
  await page.getByRole('button', { name: /^new game$/i }).click()
  await page.getByRole('button', { name: /continue/i }).click()
  await page.locator('.player-row .danger').last().click()
  for (const [index, name] of ['A', 'B', 'C', 'D', 'E'].entries()) await page.getByLabel(`Player ${index + 1} name`).fill(name)
  await page.getByRole('button', { name: /continue/i }).click()
  const farmerRow = page.locator('.role-config-row').filter({ hasText: 'Farmer' })
  const sinnerRow = page.locator('.role-config-row').filter({ hasText: 'Sinner' })
  const innkeeperRow = page.locator('.role-config-row').filter({ hasText: 'Innkeeper' })
  await page.getByRole('button', { name: /clear all/i }).click()
  await farmerRow.locator('.role-check').click()
  for (let count = 0; count < 3; count += 1) await farmerRow.locator('.stepper').nth(2).getByRole('button').last().click()
  await sinnerRow.locator('.role-check').click()
  await sinnerRow.locator('.exact-checkbox').click()
  await innkeeperRow.locator('.role-check').click()
  await innkeeperRow.locator('.exact-checkbox').click()
  await page.getByRole('button', { name: /continue/i }).click()
  await page.getByRole('button', { name: /deal roles & begin/i }).click()
  await page.getByRole('button', { name: /begin day 1/i }).click()
  await page.getByRole('button', { name: /begin first vote/i }).click()
  await page.getByLabel('A votes').fill('2')
  await page.getByLabel('B votes').fill('1')
  await page.getByLabel('C votes').fill('2')
  await page.getByRole('button', { name: /record vote/i }).click()
  await page.getByRole('button', { name: /begin ballot vote/i }).click()
  await expect(page.locator('.vote-list .tag')).toHaveCount(2)
  await expect(page.getByLabel('A votes')).toHaveValue('0')
  await expect(page.getByLabel('C votes')).toHaveValue('0')
  await expect(page.locator('.vote-meter > div').first().locator('strong')).toHaveText('0')
})

test('desktop guided editor manages reusable traits and action timing', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Desktop authoring layout')
  await page.goto('/')
  await page.getByRole('button', { name: /roles and rules/i }).click()
  await expect(page.getByRole('heading', { name: /library & editors/i })).toBeVisible()
  await page.getByRole('button', { name: /view & clone/i }).first().click()
  await expect(page.getByText('Built-ins cannot be edited directly.')).toBeVisible()
  await page.getByRole('button', { name: /clone to edit/i }).click()
  await expect(page.getByRole('heading', { name: /what counts as this role/i })).toBeVisible()
  await page.getByRole('button', { name: /new trait/i }).click()
  await page.getByLabel('Trait name').fill('Moon touched')
  await page.getByLabel('Description', { exact: true }).fill('A sample reusable trait.')
  await page.getByRole('button', { name: /create and add/i }).click()
  const dropzone = page.getByLabel('Traits on this role')
  await expect(dropzone.getByText('Moon touched')).toBeVisible()
  await page.getByRole('button', { name: /remove moon touched/i }).click()
  await page.getByRole('button', { name: /add moon touched/i }).dragTo(dropzone)
  await expect(dropzone.getByText('Moon touched')).toBeVisible()
  await page.locator('.ability-card > header').first().click()
  await expect(page.locator('.ability-card').first().locator('.ability-kind')).toHaveText('Active')
  await expect(page.locator('.ability-card').first().getByLabel('Trigger').locator('option:checked')).toHaveText('Setup action')
  await expect(page.getByLabel('Action timing')).toHaveValue('setup-information')
  await expect(page.getByText('Resolve with N0 information actions.')).toBeVisible()
  await expect(page.getByLabel('Action participants')).toHaveValue('together')
  await expect(page.getByLabel('Group label')).toHaveValue('Wolf Pack')
  await expect(page.getByLabel('Spoken action')).toHaveValue('meet the Pack')
})

test('installed shell reloads while offline', async ({ page, context }) => {
  await page.goto('/')
  await page.evaluate(async () => { if ('serviceWorker' in navigator) await navigator.serviceWorker.ready })
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading', { name: /wherewolf moderator/i })).toBeVisible()
  await context.setOffline(false)
})
